### ISSUE TITLE
Saludos, Favor regalame el scrip.sql de la base de datos gracias

### ISSUE THREAD

**Issue by henrypandales** [CRLibre/FacturadorCRLibre#10]
Saludos, Favor regalame el scrip.sql de la base de datos gracias 

Me puedes ¿escribir al whatsapp +57 314 775 4208

**Comment by bvalerin** [comment]
Buenas noches Henry Pandales, 

https://github.com/CRLibre/API_Hacienda/tree/master/recursos/sql

Adjunto referencia relacionada a la base de datos, si esta respuesta resuelve el issue por favor procede a cerrarlo..! 

Saludos!
