### ISSUE TITLE
Issue en login

### ISSUE THREAD

**Issue by AndrewLCR** [CRLibre/FacturadorCRLibre#11]
Saludos! Instalé el api en un server linux con la base de datos tal y como lo indica la documentación, sin embargo al probar el facturador, cuando se inicia la sesión redirije inmediatamente al login de nuevo. En el log de la consola tengo lo siguiente:

`[crLibreApi] >> Making a post request to http://--------/api.php
crLibreApi.js:368 [crLibreApi] >> Adding w -> facturador
crLibreApi.js:368 [crLibreApi] >> Adding r -> get_companny_information_admin
crLibreApi.js:368 [crLibreApi] >> Adding iam -> aramirez
crLibreApi.js:368 [crLibreApi] >> Adding sessionKey -> SnVwdURzcUpxWThoSGRUSEdvaG55MndOQzhFRWlpMzdwWi9LMzZWM0lkb2NMRGhVdzJWQk9VVEV6ZzAzdE1yR0dPUU94YWhrbWRtTWRMVy9JZkJZV0E9PTo695CURJRL6zFy6yhNkcCTSg==
crLibreApi.js:368 [crLibreApi] >> Adding idMasterUser -> 1
crLibreApi.js:368 [crLibreApi] >> Getting from storage K: userName GOT: aramirez
crLibreApi.js:368 [crLibreApi] >> Getting from storage K: sessionKey GOT: SnVwdURzcUpxWThoSGRUSEdvaG55MndOQzhFRWlpMzdwWi9LMzZWM0lkb2NMRGhVdzJWQk9VVEV6ZzAzdE1yR0dPUU94YWhrbWRtTWRMVy9JZkJZV0E9PTo695CURJRL6zFy6yhNkcCTSg==
crLibreApi.js:295 {"resp":"-303"}
`

**Comment by henrypandales** [comment]
Donde Descargo la base de datos script.sql para instalar el sistema??

favor escribeme al wsapp +57 314 775 4208
