### ISSUE TITLE
Donde Descargo la base de datos script.sql para instalar el sistema??

### ISSUE THREAD

**Issue by henrypandales** [CRLibre/FacturadorCRLibre#15]
favor me escribes a mi cel +57 314 775 4208 
gracias

**Comment by bvalerin** [comment]
Buenas noches Henry Pandales,

https://github.com/CRLibre/API_Hacienda/tree/master/recursos/sql

Adjunto referencia relacionada a la base de datos, si esta respuesta resuelve el issue por favor procede a cerrarlo..!

Saludos!
